### ISSUE TITLE
Make the remove options hotkeyable instead of clickable + add support for ring of shadows

### ISSUE THREAD

**Issue by red-eye-jedi** [vikke1234/charge-calc#4]
great plugin, would be a lot more useful if didnt have to manually click and was able to hotkey also adding support for the ring of shadows would be great

**Comment by vikke1234** [comment]
Hi, sadly having to manually click is in order to have it ToS compliant, there was a change to add a separate button to be able to "press enter" with it. But they weren't comfortable adding it to pluginhub. 

Ring of shadows is added, I just haven't had the time to add it to pluginhub.

**Comment by vikke1234** [comment]
Added in https://github.com/runelite/plugin-hub/pull/4990

**Comment by vikke1234** [comment]
Merged into pluginhub, closing.
