### ISSUE TITLE
Add hotkey for custom entry

### ISSUE THREAD

**Issue by WLoumakis** [vikke1234/charge-calc#5]
Would be nice to have the ability to use a hotkey for choosing whether to fill or do a -X action.

I believe this would just involve adding an `enum` `@ConfigItem` to the Config with {OFF, REMOVE, FILL} as the enum items, as well as a `@ConfigItem` that returns `Keybind`.

Then in the Plugin.java in `showWidget()` you would conditionally add a `setOnKeyListener` depending on the enum config item state that either the fill callback or the -X callback, assuming the key pressed matches the Keybind config item.

Let me know what you think and/or if you have any questions. More than happy to help if needed!

**Comment by vikke1234** [comment]
I can add this at some point, I'm quite busy currently. It's a bit unclear if this would be accepted into PH though as a similar thing was implemented earlier but was rejected.

See https://github.com/runelite/plugin-hub/pull/4848

**Comment by WLoumakis** [comment]
Ah okay, the other one looks quite similar to what I'd like and since it got denied I suppose this one would too. No worries!

**Comment by vikke1234** [comment]
added.
