### ISSUE TITLE
Can't use numpad for typing numbers

### ISSUE THREAD

**Issue by JZomDev** [vikke1234/charge-calc#7]
When plugin is on, you cannot use numpad to type in the charges you want to use, normal numbers work fine.

**Comment by JZomDev** [comment]
It looks like it's fixed in the current version here on the repo but not what is in the hub.

**Comment by vikke1234** [comment]
it's being PRed currently, see: https://github.com/runelite/plugin-hub/pull/6123

**Comment by vikke1234** [comment]
Fixed now, closing.
