### ISSUE TITLE
Duplicate charge entry

### ISSUE THREAD

**Issue by KingPatVII** [vikke1234/charge-calc#9]
When applying charges to items (sanguinesti/shadow/blowpipe etc.) all typed inputs (number of charges I wish to apply) are duplicated upon entry - ie

Attempting to put in 4500 charges; I type '4', but '44' is the prompted input, when I backspace and type '5', '55' is entered, backspace again such that my prompt is '45' now and I type '0', '00' is entered. 

I was able to reproduce the error with all charged items I have (sanguinesti/shadow/blowpipe/accursed/webweaver/scythe/venator). When I turn the plugin off the error is eliminated, It does not affect any other part of gameplay or user experience. 

I have restarted plugin and client, to no success.

**Comment by vikke1234** [comment]
Hi,

Is this still an issue, I pushed a patch a week ago or so.

**Comment by vikke1234** [comment]
closing since no update.
